### ISSUE TITLE
Local collector: Paket wird nicht entfernt, wenn Datei außerhalb des Ordners verschoben wurde

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/questionpy-server#31]
Beim `FileMovedEvent` wird aktuell nicht überprüft, in welchen Ordner die Datei verschoben wurde. Wenn die Datei außerhalb des eingestellten `local_directory` liegt, sollte das Paket intern vom Local Collector entfernt werden.

**Comment by janbritz** [comment]
Wenn ein Paket in einen anderen Ordner verschoben wird, wird nicht das `FileMovedEvent`, sondern das `FileDeletedEvent` getriggert.
